{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nginx-demo.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nginx-demo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    any: true
{{- end }}
