apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-demo.fullname" . }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-demo.selectorLabels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
      {{- end }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
            {{- if .Values.metrics.enabled }}
            - name: nginx-status-conf
              mountPath: /etc/nginx/conf.d/status.conf
              subPath: status.conf
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:1.4"
          args:
            - --nginx.scrape-uri=http://localhost:8080/stub_status
          ports:
            - name: http-metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
        {{- end }}
      volumes:
        - name: html-volume
          configMap:
            name: {{ include "nginx-demo.fullname" . }}-html
        {{- if .Values.metrics.enabled }}
        - name: nginx-status-conf
          configMap:
            name: {{ include "nginx-demo.fullname" . }}-html
            items:
              - key: status.conf
                path: status.conf
        {{- end }}
